name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: acrmarch2021.azurecr.io/march21
      credentials:
        username: acrmarch2021
        password: +/1qsMB7o+ti=pR1f/iVva=hy1s+YkCM

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
