name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest     
    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
          username: acrmarch2021 
          password: +/1qsMB7o+ti=pR1f/iVva=hy1s+YkCM 
          login-server: acrmarch2021.azurecr.io
    - name: Build and push Docker images ACR
      uses: docker/build-push-action@v2.3.0
      with:
        load: true
        tags: acrmarch2021.azurecr.io/march23
    - name: Build and push Docker images GHCR
      uses: docker/build-push-action@v2.3.0
      with:
        load: true
        tags: ghcr.io/hamzamarch/march23ghcr
    - name: push ACR
      run: docker push acrmarch2021.azurecr.io/march23
    - name: Authenticate to GHCR
      run: $ echo $CR_PAT | docker login ghcr.io/hamzamarch
    - name: push GHCR
      run: docker push ghcr.io/hamzamarch/march23ghcr
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        allow-no-subscriptions: true
    - name: Deploy to Azure Container Instances
      uses: Azure/aci-deploy@v1
      with:
        name: mycontainer1
        location: eastus
        dns-name-label: mylabelmarch202123
        resource-group: original
        image: acrmarch2021.azurecr.io/march23
        registry-login-server: acrmarch2021.azurecr.io
        registry-username: acrmarch2021
        registry-password: +/1qsMB7o+ti=pR1f/iVva=hy1s+YkCM
        
